### ISSUE TITLE
thoughts about aggregation functions?

### ISSUE THREAD

**Issue by tve** [anywhichway/rule-reactor#13]
Have you considered implementing aggregation functions, i.e., functions that can be used in rule conditions and that perform a reduction across all facts that match a pattern? What I mean is something like Drool's accumulate function. A simple example might be:

```
reactor.createRule("free-homes", 0, {h: Home},
  function(h) { return reactor.reduce({home: Home}, function(sum, home) {
    return sum + (occupants == 0 ? 1 : 0);
  });},
  function(h) { console.log("there are", n, "free homes"); }); // need to bind n to the result of reduce
```

An efficient implementation may need two delta functions passed to `reduce` in order to add a fact to the sum and in order to remove one, at least that's what drools does.

**Comment by anywhichway** [comment]
It is more likely we would provide access to the LHS bindings in the RHS so that you could do the aggregation with normal Javascript functions. Still researching the RHS binding exposure per the other issue.

**Comment by tve** [comment]
> It is more likely we would provide access to the LHS bindings in the RHS so that you could do the aggregation with normal Javascript functions.

The idea being that if the LHS uses exists() then the RHS would receive an array of all the facts for which the condition is true? That would work nicely indeed.

**Comment by anywhichway** [comment]
Exactly

**Comment by anywhichway** [comment]
Does the .instances property mentioned in #14 address this need adequately? If so, you can close this issue.
