### ISSUE TITLE
Q: nested objects

### ISSUE THREAD

**Issue by tve** [anywhichway/rule-reactor#2]
Sorry for posting questions here, if there is a better forum, please let me know.

Does rule-reactor support nested objects? For example, starting with your patient example (https://github.com/anywhichway/rule-reactor/blob/master/examples/patient.html), suppose I add
```
function Address() {
  this.street = null
  this.city = null
}
```
and then in the constructor for Patient I set `this.home = new Address()` can I then write rules with conditions such as
```
function(p) { return p.address.city == "Los Angeles"; }
```
or perhaps more interesting:
```
reactor.createRule("SameCity", 0, {p: Patient, d:Doctor},
  function(p, d) { return p.address.city == d.address.city; }
  ...
);
```
maybe Address shouldn't be an object but just a simple hash?

A related question is: is it possible for a `Patient` could have an array of addresses and a rule that iterates over the addresses and fires if the doctor's address is in the same city as one of them?

Yet another question I have is whether it is possible to add an object model at run-time?

**Comment by anywhichway** [comment]
This is the correct forum. We will split your questions into separate issues and answer them or ask for clarification over the next couple of days.

**Comment by anywhichway** [comment]
Split into issues 3,4, and 5 for clarity.
