### ISSUE TITLE
Property 'instances' is shared between subclasses

### ISSUE THREAD

**Issue by Zelgadis87** [anywhichway/rule-reactor#21]
It seems like if two classes in the domain of RuleReactor share the same ES6 parent class, their 'instances' property contains instances of both classes.  
My setup is quite complex, but to simplify, I have created a base class shared by many of my domain objects, to refactor most of the complexity of the rules. 
```
class Base {
	constructor() {
		this.parent = null;
		this.children = [];
		this.accepted = false;
		this.processed = false;
	}
}
class TextMessage extends Base {
	constructor() { super(); }
}
class AudioMessage extends Base {
	constructor() { super(); }
}
```
If I then do TextMessage.instances, I find both TextMessage and AudioMessage instances, and viceversa.  
I have attempted a fix on my fork of the project, which seems to work, but I'm afraid I have no idea if I have introduced regressions or the behavior was intended.

**Comment by Zelgadis87** [comment]
Thinking about it some more, I'm afraid my solution will have 0 instances registered for the super class, which might break stuff unexpectedly. A more invasive solution would be required to address both issues.

**Comment by anywhichway** [comment]
Thanks. We will look into this over the next week.

**Comment by anywhichway** [comment]
@Zelgadis87 we are testing your patch right now. There was a minor error, you made the index and array, it is a regular object map. There were also three other locations in the code it needed to be addressed. Below is the code we are using. You are correct about the issue with no instances being registered to the superclass. We have a sense regarding how to fix this, i.e. insert a tree walker every place we reference instances. However, if this passes regression, we will push a fix and document that superclasses may not match properly. This will at least allow you to have simpler rules. If you do need to match instances on a superclass, you will need to use or conditions in a rule and match against the children.

```
if ( !cons.hasOwnProperty('instances') ) cons.instances = [];
if ( !cons.hasOwnProperty('index') ) cons.index = {};
```

**Comment by anywhichway** [comment]
@Zelgadis87 this has been pushed to the master branch as v0.1.10.
