### ISSUE TITLE
Property 'instances' is never cleared on domain object prototypes

### ISSUE THREAD

**Issue by TonyFNZ** [anywhichway/rule-reactor#23]
When a fact is asserted it is added to the `instances` collection for the domain object prototype.  However, when the fact is retracted it is not removed from this collection.  This results in a memory leak as this collection gets bigger and bigger.

I believe this issue may have been introduced by the fix for #21, however I am still investigating.  

I think the fix would be to update the `retract` function to clean up the instances array.

**Comment by anywhichway** [comment]
@TonyFNZ Thanks! Looking into it.

**Comment by anywhichway** [comment]
@TonyFNZ This has been fixed in v0.1.11. It will be pushed to NPM once one of you have verified.

**Comment by anywhichway** [comment]
Pushed to npmjs.
