### ISSUE TITLE
 Is possible to add an object model at run-time? (From Issue 2)

### ISSUE THREAD

**Issue by anywhichway** [anywhichway/rule-reactor#5]
Is possible to add an object model at run-time?

**Comment by anywhichway** [comment]
@tve please clarify the question

**Comment by tve** [comment]
Taking the patient example (https://github.com/anywhichway/rule-reactor/blob/master/examples/patient.html), there are four steps: first define the domain models (Patient, Diagnosis, Treatment), then define the rules (`reactor.createRule(...)`), then define some facts (`reactor.assert(...)`) and finally call `reactor.run()`.
The way I'd like to run rule-reactor is in an HTTP service where new domain models, new rules, and new facts can arrive at any point in time. So the question I have is whether additional domain models and rules can be added after one iteration of `reactor.run()`, and also whether domain models and rules can be removed.
I'm also wondering how to best use rule-reactor in a system where facts arrive dynamically at run-time, e.g. through HTTP requests.

**Comment by anywhichway** [comment]
Object constructors need to be defined before rules that reference instances of the objects. If you don't at least define the constructor, then the domain section of a rule definition will not have anything to reference.

Properties with values can be added to objects dynamically and rules referencing the property will be fired regardless of when the rule was defined so long as the property is either added before the object is asserted or added as a result of a rule action.

Rules can be added at any time. They can even be created by other rules.

To handle dynamic arrival of facts, convert the inbound data into a Javascript object and use reactor.assert or add it to an existing property on an already asserted object.

**Comment by tve** [comment]
I clearly have to dig into the rule-reactor code to understand how things work (and get up on the learning curve of node.js), but could you provide a sketch for how you would structure an http service around rule-reactor? Things I'm wondering:

- assume the HTTP interface allows facts to be modified, for example, change the address of a patient, is it best to implement this by updating the appropriate fact object or is it better to retract the entire patient fact and assert a new one? (Assuming that some rules on Patients don't need to fire if just the address changes.)

- how do I run the main loop that accepts HTTP requests and runs rule-reactor? I assume that running rule-reactor with an Infinity parameter after every HTTP request would be too slow. So do I try to dynamically converge on some number of rule firings passed into reactor.run so it runs for a few ms and then relinquishes control so HTTP requests can be accepted?

**Comment by anywhichway** [comment]
Thorsten, could you split your question into two issues? This will help in focusing and answer and also result in a more consumable knowledge base by others.

**Comment by tve** [comment]
done, I hope this is the split you wanted, #6
