### ISSUE TITLE
modifying fact attributes/fields vs retracting & re-asserting

### ISSUE THREAD

**Issue by tve** [anywhichway/rule-reactor#7]
When attributes of a fact change, for example, the address of a patient, is it best to implement this by updating the appropriate fact object or is it better to retract the entire patient fact and assert a new one? (Assuming that some rules on Patients don't need to fire if just the address changes.)

**Comment by anywhichway** [comment]
It is better to just modify the property on the object rather than retract the entire patient object and re-assert.
